import pytest

from macuitest.config.constants import Region
from macuitest.lib.elements.locators.capture import Entry
from macuitest.lib.elements.locators.capture import Found
from macuitest.lib.elements.locators.capture import attribute_name
from macuitest.lib.elements.locators.capture import class_name
from macuitest.lib.elements.locators.capture import crop_box
from macuitest.lib.elements.locators.capture import locator_for
from macuitest.lib.elements.locators.capture import plan
from macuitest.lib.elements.locators.capture import render_module

FRAME = Region(0, 0, 10, 10)


def test_an_identifier_is_the_preferred_locator():
    seven = Found("AXButton", FRAME, identifier="Seven", description="7")

    assert locator_for(seven, [seven]) == ('ax(identifier="Seven", kind=Button)', "Button")


def test_a_shared_identifier_falls_back_to_description_for_later_elements():
    first = Found("AXButton", FRAME, identifier="Key", description="7")
    second = Found("AXButton", FRAME, identifier="Key", description="8")

    assert locator_for(first, [first, second])[0] == 'ax(identifier="Key", kind=Button)'
    assert locator_for(second, [first, second])[0] == (
        'ax(description="8", role="AXButton", kind=Button)'
    )


def test_a_role_filter_doesnt_change_which_locator_resolves():
    earlier = Found("AXButton", FRAME, description="OK")
    later = Found("AXButton", FRAME, description="OK", title="Confirm")

    entries = plan(kept=[later], walked=[earlier, later])

    assert entries[0].locator == 'ax(title="Confirm", role="AXButton", kind=Button)'


def test_an_element_without_usable_attributes_gets_an_image():
    blank = Found("AXGroup", FRAME)

    assert locator_for(blank, [blank]) == ("image()", None)


def test_roles_without_a_native_class_get_no_kind():
    group = Found("AXGroup", FRAME, identifier="Keypad")

    assert locator_for(group, [group]) == ('ax(identifier="Keypad")', None)


@pytest.mark.parametrize(
    "found, expected",
    [
        (Found("AXButton", FRAME, identifier="AllClear"), "all_clear"),
        (Found("AXButton", FRAME, description="7"), "button_7"),
        (Found("AXButton", FRAME, title="App"), "app_"),
        (Found("AXButton", FRAME, title="Window"), "window_"),
        (Found("AXButton", FRAME, title="class"), "class_"),
        (Found("AXButton", FRAME, description="Готово"), "button"),
        (Found("AXGroup", FRAME), "group"),
    ],
)
def test_attribute_names_are_valid_and_dont_shadow_screen(found, expected):
    assert attribute_name(found, set()) == expected


def test_attribute_names_get_a_suffix_on_collision():
    taken: set[str] = set()
    names = [attribute_name(Found("AXButton", FRAME, title="OK"), taken) for _ in range(3)]

    assert names == ["ok", "ok_2", "ok_3"]


def test_crop_box_adds_the_margin_in_pixels():
    window = Region(100, 100, 300, 300)

    assert crop_box(Region(150, 150, 170, 160), window, margin=4, scale=2) == (92, 92, 56, 36)


def test_crop_box_clips_to_the_window():
    window = Region(100, 100, 300, 300)

    assert crop_box(Region(100, 290, 120, 300), window, margin=4, scale=1) == (0, 186, 24, 14)


def test_crop_box_outside_the_window_is_none():
    assert crop_box(Region(400, 400, 410, 410), Region(0, 0, 100, 100), margin=4, scale=1) is None


@pytest.mark.parametrize(
    "title, app, expected",
    [
        ("Calculator", "Calculator", "Calculator"),
        ("", "System Settings", "SystemSettings"),
        (None, "1Password", "AppScreen"),
    ],
)
def test_class_name(title, app, expected):
    assert class_name(title, app) == expected


def test_render_module_writes_an_importable_screen():
    entries = [
        Entry("seven", 'ax(identifier="Seven", kind=Button)', "Button", Found("AXButton", FRAME)),
        Entry("logo", "image()", None, Found("AXImage", FRAME)),
    ]

    source = render_module("Calculator", "Calculator", entries)

    assert source == (
        '"""Generated by `python -m macuitest.locators capture "Calculator"`. Edit freely."""\n'
        "\n"
        "from macuitest.lib.elements.locators import Screen\n"
        "from macuitest.lib.elements.locators import ax\n"
        "from macuitest.lib.elements.locators import image\n"
        "from macuitest.lib.elements.native_element import Button\n"
        "\n"
        "\n"
        'class Calculator(Screen, app="Calculator"):\n'
        '    seven = ax(identifier="Seven", kind=Button)\n'
        "    logo = image()\n"
    )
    compile(source, "calculator.py", "exec")


def test_render_module_without_entries_is_still_valid():
    source = render_module("Calculator", "Calculator", [])

    assert source.endswith("    pass\n")
    compile(source, "calculator.py", "exec")


def test_render_module_declares_the_window_of_a_window_screen():
    from macuitest.lib.elements.locators.accessibility import AXQuery

    entries = [
        Entry(
            "empty",
            'ax(title="Empty Trash", role="AXButton", kind=Button)',
            "Button",
            Found("AXButton", FRAME),
        )
    ]

    source = render_module("Finder", "Finder", entries, window=AXQuery.of(subrole="AXDialog"))

    assert "from macuitest.lib.elements.locators import window\n" in source
    assert 'class Finder(Screen, app="Finder", window=window(subrole="AXDialog")):\n' in source
    compile(source, "finder.py", "exec")
