import cv2
import pytest

from macuitest.config.constants import Region
from macuitest.lib.elements.locators import capture as capture_module
from macuitest.lib.elements.locators.accessibility import AXQuery
from macuitest.lib.elements.locators.capture import capture
from macuitest.lib.elements.locators.capture import walk
from macuitest.lib.elements.locators.capture import window_number
from macuitest.lib.elements.native.calls import AXErrorFailure


class FakeAX:
    """An accessibility element with fixed attributes."""

    def __init__(self, *children, **attributes):
        self.attributes = {"AXChildren": list(children), **attributes}
        self.pid = 42

    def get_ax_attribute(self, name):
        return self.attributes.get(name)


def element(role, x, y, width, height, **attributes):
    return FakeAX(AXRole=role, AXPosition=(x, y), AXSize=(width, height), **attributes)


def calculator_window():
    """A 200x100 pt window at (10, 20) with a button, a label, chrome, and an off-window item."""
    return FakeAX(
        element("AXButton", 30, 40, 60, 24, AXIdentifier="OK"),
        element("AXStaticText", 100, 40, 50, 20, AXDescription="Total"),
        element("AXButton", 12, 22, 10, 10, AXSubrole="AXCloseButton"),
        element("AXButton", 500, 40, 60, 24, AXIdentifier="Hidden"),
        AXRole="AXWindow",
        AXTitle="Calculator",
        AXPosition=(10, 20),
        AXSize=(200, 100),
    )


@pytest.fixture
def app(monkeypatch, text_image):
    """Serve calculator_window as Calculator's window, captured at 2x, and record queries."""
    queries = []

    def standard_window(name, query=None):
        queries.append(query)
        return calculator_window()

    monkeypatch.setattr(capture_module, "standard_window", standard_window)
    monkeypatch.setattr(capture_module, "window_number", lambda pid, frame: 7)
    monkeypatch.setattr(
        capture_module.monitor, "capture_window", lambda number: text_image([], 200, 100)
    )
    return queries


def test_walk_skips_window_chrome():
    roles = [(found.role, found.identifier) for found in walk(calculator_window())]

    assert roles == [("AXButton", "OK"), ("AXStaticText", None), ("AXButton", "Hidden")]


class SwiftUIToolbarButton(FakeAX):
    """A button whose AXSubrole read fails while its other attributes read fine."""

    def get_ax_attribute(self, name):
        if name == "AXSubrole":
            raise AXErrorFailure("There is some sort of system memory failure")
        return super().get_ax_attribute(name)


def test_walk_keeps_an_element_with_an_unreadable_attribute():
    button = SwiftUIToolbarButton(
        AXRole="AXButton", AXDescription="Mode", AXPosition=(30, 40), AXSize=(20, 20)
    )

    found = walk(FakeAX(FakeAX(button, AXRole="AXToolbar")))

    assert [(f.role, f.description) for f in found] == [("AXButton", "Mode")]


def test_capture_writes_a_module_and_a_png_per_element_inside_the_window(app, tmp_path):
    out = tmp_path / "calculator.py"

    written = capture("Calculator", out)

    folder = tmp_path / "calculator" / "calculator"
    assert written == [out, folder / "ok.png", folder / "total.png"]
    assert 'ok = ax(identifier="OK", kind=Button)' in out.read_text()
    png = cv2.imread(str(folder / "ok.png"))
    assert png is not None
    # 60x24 pt plus 4 pt on each side, at 2x.
    assert png.shape[:2] == (64, 136)


def test_capture_keeps_only_the_given_roles(app, tmp_path):
    out = tmp_path / "calculator.py"

    capture("Calculator", out, roles=["AXStaticText"])

    assert "ok =" not in out.read_text()
    assert "total =" in out.read_text()


def test_capture_of_a_window_screen_declares_its_window(app, tmp_path):
    out = tmp_path / "finder.py"
    dialog = AXQuery.of(subrole="AXDialog")

    capture("Finder", out, window=dialog)

    assert app == [dialog]
    assert 'app="Finder", window=window(subrole="AXDialog")' in out.read_text()


def test_capture_writes_nothing_when_a_target_exists(app, tmp_path):
    out = tmp_path / "calculator.py"
    existing = tmp_path / "calculator" / "calculator" / "ok.png"
    existing.parent.mkdir(parents=True)
    existing.write_bytes(b"mine")

    with pytest.raises(FileExistsError, match="--force"):
        capture("Calculator", out)

    assert not out.exists()
    assert not (existing.parent / "total.png").exists()
    assert existing.read_bytes() == b"mine"


def test_capture_with_force_replaces_existing_files(app, tmp_path):
    out = tmp_path / "calculator.py"
    out.write_text("mine")

    capture("Calculator", out, force=True)

    assert out.read_text().startswith('"""Generated by')


def test_capture_needs_a_window(monkeypatch, tmp_path):
    monkeypatch.setattr(capture_module, "standard_window", lambda name, query=None: None)

    with pytest.raises(LookupError, match="Calculator has no matching window"):
        capture("Calculator", tmp_path / "calculator.py")


def test_capture_needs_an_element_of_the_given_roles(app, tmp_path):
    with pytest.raises(LookupError, match="AXSlider"):
        capture("Calculator", tmp_path / "calculator.py", roles=["AXSlider"])


def test_capture_rejects_a_negative_margin(tmp_path):
    with pytest.raises(ValueError, match="margin"):
        capture("Calculator", tmp_path / "calculator.py", margin=-1)


def test_window_number_matches_the_owner_and_bounds(monkeypatch):
    bounds = {"X": 10, "Y": 20, "Width": 200, "Height": 100}
    windows = [
        {
            "kCGWindowOwnerPID": 42,
            "kCGWindowLayer": 25,
            "kCGWindowNumber": 1,
            "kCGWindowBounds": bounds,
        },
        {
            "kCGWindowOwnerPID": 7,
            "kCGWindowLayer": 0,
            "kCGWindowNumber": 2,
            "kCGWindowBounds": bounds,
        },
        {
            "kCGWindowOwnerPID": 42,
            "kCGWindowLayer": 0,
            "kCGWindowNumber": 3,
            "kCGWindowBounds": bounds,
        },
    ]
    monkeypatch.setattr(capture_module.Quartz, "CGWindowListCopyWindowInfo", lambda *args: windows)

    assert window_number(42, Region(10, 20, 210, 120)) == 3
    assert window_number(42, Region(0, 0, 50, 50)) is None
